### PR TITLE
[WIP] #50 dockerized front and backend

### LINKED ISSUE #50: Add docker support

### PR DESCRIPTION
**Pull request by EzxD**
Close #50

### CODE REVIEW

**Review by steve-hb — APPROVED** [review]

**Comment by EzxD** [comment]
could someone take a look on the backend docker?

**Comment by EzxD** [comment]
I get the following error:
``` => ERROR [development 6/6] RUN npm run build                                                                                                            1.3s
------
 > [development 6/6] RUN npm run build:
#12 0.979
#12 0.979 > babylon-backend@1.0.0 build /usr/src/app
#12 0.979 > nest build
#12 0.979
#12 1.000 internal/modules/cjs/loader.js:883
#12 1.000   throw err;
#12 1.000   ^
#12 1.000
#12 1.000 Error: Cannot find module 'ansi-styles'
#12 1.000 Require stack:
#12 1.000 - /usr/src/app/node_modules/chalk/source/index.js
#12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js
#12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/index.js
#12 1.000 - /usr/src/app/node_modules/@nestjs/cli/bin/nest.js
#12 1.000     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
#12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
#12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19)
#12 1.000     at require (internal/modules/cjs/helpers.js:88:18)
#12 1.000     at Object.<anonymous> (/usr/src/app/node_modules/chalk/source/index.js:2:20)
#12 1.000     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#12 1.000     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
#12 1.000     at Module.load (internal/modules/cjs/loader.js:928:32)
#12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
#12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19) {
#12 1.000   code: 'MODULE_NOT_FOUND',
#12 1.000   requireStack: [
#12 1.000     '/usr/src/app/node_modules/chalk/source/index.js',
#12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js',
#12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/index.js',
#12 1.000     '/usr/src/app/node_modules/@nestjs/cli/bin/nest.js'
#12 1.000   ]
#12 1.000 }
#12 1.003 npm ERR! code ELIFECYCLE
#12 1.003 npm ERR! errno 1
#12 1.004 npm ERR! babylon-backend@1.0.0 build: `nest build`
#12 1.004 npm ERR! Exit status 1
#12 1.004 npm ERR!
#12 1.004 npm ERR! Failed at the babylon-backend@1.0.0 build script.
#12 1.004 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#12 1.043
#12 1.043 npm ERR! A complete log of this run can be found in:
#12 1.043 npm ERR!     /root/.npm/_logs/2021-04-15T09_53_17_506Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1```

using node:14.16.1-alpine

**Comment by Floppy012** [comment]
> I get the following error:
> 
> ```
> ------
>  > [development 6/6] RUN npm run build:
> #12 0.979
> #12 0.979 > babylon-backend@1.0.0 build /usr/src/app
> #12 0.979 > nest build
> #12 0.979
> #12 1.000 internal/modules/cjs/loader.js:883
> #12 1.000   throw err;
> #12 1.000   ^
> #12 1.000
> #12 1.000 Error: Cannot find module 'ansi-styles'
> #12 1.000 Require stack:
> #12 1.000 - /usr/src/app/node_modules/chalk/source/index.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/index.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/bin/nest.js
> #12 1.000     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
> #12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
> #12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19)
> #12 1.000     at require (internal/modules/cjs/helpers.js:88:18)
> #12 1.000     at Object.<anonymous> (/usr/src/app/node_modules/chalk/source/index.js:2:20)
> #12 1.000     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> #12 1.000     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> #12 1.000     at Module.load (internal/modules/cjs/loader.js:928:32)
> #12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> #12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19) {
> #12 1.000   code: 'MODULE_NOT_FOUND',
> #12 1.000   requireStack: [
> #12 1.000     '/usr/src/app/node_modules/chalk/source/index.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/index.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/bin/nest.js'
> #12 1.000   ]
> #12 1.000 }
> #12 1.003 npm ERR! code ELIFECYCLE
> #12 1.003 npm ERR! errno 1
> #12 1.004 npm ERR! babylon-backend@1.0.0 build: `nest build`
> #12 1.004 npm ERR! Exit status 1
> #12 1.004 npm ERR!
> #12 1.004 npm ERR! Failed at the babylon-backend@1.0.0 build script.
> #12 1.004 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> #12 1.043
> #12 1.043 npm ERR! A complete log of this run can be found in:
> #12 1.043 npm ERR!     /root/.npm/_logs/2021-04-15T09_53_17_506Z-debug.log
> ------
> executor failed running [/bin/sh -c npm run build]: exit code: 1```
> 
> using node:14.16.1-alpine
> ```

This is probably because you use install only dev dependencies in your [Dockerfile](https://github.com/cntitanium/babylon/pull/51/files#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486R22)

**Comment by Floppy012** [comment]
> I get the following error:
> 
> ```
> ------
>  > [development 6/6] RUN npm run build:
> #12 0.979
> #12 0.979 > babylon-backend@1.0.0 build /usr/src/app
> #12 0.979 > nest build
> #12 0.979
> #12 1.000 internal/modules/cjs/loader.js:883
> #12 1.000   throw err;
> #12 1.000   ^
> #12 1.000
> #12 1.000 Error: Cannot find module 'ansi-styles'
> #12 1.000 Require stack:
> #12 1.000 - /usr/src/app/node_modules/chalk/source/index.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/commands/index.js
> #12 1.000 - /usr/src/app/node_modules/@nestjs/cli/bin/nest.js
> #12 1.000     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
> #12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
> #12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19)
> #12 1.000     at require (internal/modules/cjs/helpers.js:88:18)
> #12 1.000     at Object.<anonymous> (/usr/src/app/node_modules/chalk/source/index.js:2:20)
> #12 1.000     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> #12 1.000     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> #12 1.000     at Module.load (internal/modules/cjs/loader.js:928:32)
> #12 1.000     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> #12 1.000     at Module.require (internal/modules/cjs/loader.js:952:19) {
> #12 1.000   code: 'MODULE_NOT_FOUND',
> #12 1.000   requireStack: [
> #12 1.000     '/usr/src/app/node_modules/chalk/source/index.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/command.loader.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/commands/index.js',
> #12 1.000     '/usr/src/app/node_modules/@nestjs/cli/bin/nest.js'
> #12 1.000   ]
> #12 1.000 }
> #12 1.003 npm ERR! code ELIFECYCLE
> #12 1.003 npm ERR! errno 1
> #12 1.004 npm ERR! babylon-backend@1.0.0 build: `nest build`
> #12 1.004 npm ERR! Exit status 1
> #12 1.004 npm ERR!
> #12 1.004 npm ERR! Failed at the babylon-backend@1.0.0 build script.
> #12 1.004 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> #12 1.043
> #12 1.043 npm ERR! A complete log of this run can be found in:
> #12 1.043 npm ERR!     /root/.npm/_logs/2021-04-15T09_53_17_506Z-debug.log
> ------
> executor failed running [/bin/sh -c npm run build]: exit code: 1```
> 
> using node:14.16.1-alpine
> ```

This is probably because you try to build with only the development dependencies: https://github.com/cntitanium/babylon/pull/51/files#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486R7

The system is intended to be used the other way around. You need dev and prod dependencies to build the app. But you only need the prod dependencies to run the app.

You either have to build the app outside the container, then copy it into the container and then call `npm install --only=prod` or you have to remove the `node_modules` directory after build and then reinstall only production dependencies.

**Comment by steve-hb** [comment]
Closed in favor of #60

**Pull request closed without merging**
